### ISSUE TITLE
Edit hotkeys?

### ISSUE THREAD

**Issue by Skinnytorus** [framefield/tooll#11]
Hi,
I'd like to be able to edit default key bindings. How do I do that?
I would also like to visualize operators in 3d viewport by a keyboard shortcut (not by left-clicking on it).

PS I'm used to the werkkzeug way of working with operators and my life with the Tooll would be a lot easier if I could define a similar keboard layout scheme.

**Comment by pixtur** [comment]
Hi. Sadly editing the keyboard-mapping will be a very hard thing to do, because the bindings are scattered all over the place. To implement this feature one would have to insert a complete wrapper over all views and refactor all keyboard-usage throughout the application, probably including Modifier-keys like CTRL, SHIFT and ALT. This would be a very big tasks and I'm not really sure, it has top priority right now.

I can feel your pain, and yes we should have started this earlier...

What do you mean by that...

> I would also like to visualize operators in 3d viewport by a keyboard shortcut (not by left-clicking on it).

**Comment by Skinnytorus** [comment]
That's too bad... I will be super happy to see that feature in future.

> What do you mean by that...

In werkkzeug a stack of operators doesn't show it's result in 3d view until you select any operator and press 's' (unlike Tooll, they are stacked from top to bottom). This is handy because calculating an operator stack might take a while and pressing a button on the keyboard makes you kinda ready for a few miliseconds (or even seconds if the stack is large) of delay. IMO it's a good idea to 'separate' working with the operator tree (mostly a mouse work) from visualizing the result on screen (a keyboard shortcut).

**Comment by pixtur** [comment]
Hi. Interestingly, we had a similar concept with the same hotkey (S) and (Shift-S), because we originally looked quite close at werkzeug. Shift-S basically selects and Locks the current selection to the selection view. Maybe, if you lock both views, this already does the job...

**Comment by Skinnytorus** [comment]
Nahhhh... I can't reach the same effect as in werkkzeug. The very process behind showing a result of an operator upon clicking it seems to slow things down even on my 6 core i7 with GTX780 and 16 gigs of RAM. There must be an option to bind a shortcut (like 's' for instance) for that kind of thing.
