### ISSUE TITLE
Question: Community Forum?

### ISSUE THREAD

**Issue by Skinnytorus** [framefield/tooll#12]
You guys have any plans to set up a Tooll2 community forum for users to exchange their knowledge without bothering you?

**Comment by wirmachenbunt** [comment]
bump

and btw. great overdue move to go public

**Comment by necaremus** [comment]
i like dis idea as well, although i still need to get better gfx-hardware//stronger machine to use all functions of tooll x'D

**Comment by pixtur** [comment]
Excellent question! I would love to see a small community around tooll. There is actually no other way, because if we answer all questions, we have no more time for coding. It's a shame that github doesn't support such a thing. I'm a bit hesitant about installing a forum, though. But if some people volunteer to invest some time as moderators I will setup something.

@wirmachenbunt Thanks for the feedback. And yes, it took us a while. :-)

**Comment by Skinnytorus** [comment]
If it's possible to setup a custom forum at github, then yeeeees! I'm all for it. Not sure though if I could invest the time into moderating it...
On the other hand I might as well try to contact erbsen and perhaps he could agree to become our host at h**p://erbsen.untergrund.net/board3/ . This forum used to be home to werkkzeug fans and now it's all but abandoned. Tooll users might breathe some life into it.

**Comment by pixtur** [comment]
Hi Torus,

Although erbsen might be a good starting point, we would probable install something on our server...

**Comment by Skinnytorus** [comment]
OK then. How soon can we expect that to happen?

**Comment by pixtur** [comment]
I will be off the grid for the next 3 weeks, so probably by the end of April. For the time being I would keep on discussion with github issues.

**Comment by Skinnytorus** [comment]
OK. Accepted.

**Comment by pixtur** [comment]
Tataaa: It took us a while, but here you go: [https://forums.tooll.io](https://forums.tooll.io)

**Comment by Skinnytorus** [comment]
hi, pixtur.
https doesn't work for me. This link works only as: http://forums.tooll.io/
