### ISSUE TITLE
Question: Control sound volume?

### ISSUE THREAD

**Issue by Skinnytorus** [framefield/tooll#20]
Hi, guys.
Is there a way to control the sound volume?

**Comment by pixtur** [comment]
You mean from the main soundtrack? No, not yet. What is your use case?

**Comment by Skinnytorus** [comment]
My case is as commonplace as it can be. I just wanna make the music less distracting :)

**Comment by pixtur** [comment]
Understandable. But why not use Windows' sound mixer then? In the long run, we need to replace the project audio track with an "audioclip" operator with parameters for volume, time and speed that can be animated.

**Comment by Skinnytorus** [comment]
Thanks. That would be just great!
PS Most of my grouses seem based on subconscious comparison to werkkzeug :))

**Comment by pixtur** [comment]
Haha, I don't mind. I'm taking to be compared to Werkkzeug as a compliment. Fiver and Chaos did an awesome job. I can still remember how furious I was when the creeps at wikipedia removed the  article because they thought it to be "not significant" enough. Without Werkkzeug and vvvv there wouldn't be TOOLL.io. But then again, we did move on quiet a bit from there.

**Comment by Skinnytorus** [comment]
Man... You are pushing the boundaries that existed in werkkzeug and that's a kind of thing I admire.
